services:
  - type: web
    name: edulive-laravel
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    dockerContext: .
    buildCommand: ""
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://edulive.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromService:
          name: edulive-mysql
          type: pserv
          property: host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: edulive
      - key: DB_USERNAME
        fromDatabase:
          name: edulive-mysql
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: edulive-mysql
          property: password
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_API_BASE
        value: https://api.openai.com/v1
      - key: OPENAI_MODEL
        value: gpt-4o

databases:
  - name: edulive-mysql
    databaseName: edulive
    plan: free
